# Nome do workflow
name: Build and Release Executable

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    # Continua rodando no Windows para gerar o .exe
    runs-on: windows-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Altere para a sua versão do Python

      # 3. Instala as dependências e o PyInstaller
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      # 4. Roda o PyInstaller para criar o executável
      - name: Build executable with PyInstaller
        run: |
          # Altere 'main.py' para o nome do seu script principal
          # e --name para o nome do seu executável.
          pyinstaller --onefile --windowed --name="ConversorSQL" main.py

      # 5. (NOVO) Cria o Release no GitHub e anexa o .exe
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # O corpo do release pode ser gerado automaticamente com as últimas mensagens de commit
          generate_release_notes: true
          # Anexa o .exe gerado ao release.
          # O caminho deve corresponder exatamente ao que foi definido no passo anterior.
          files: dist/ConversorSQL.exe